package com.incomm.wmp.gprServices.constants;

/**
 * Created by dvontela on 8/9/2017.
 */
public enum UserEvents {
    LOGIN,
    MONTHLYTRANSACTION,
    CURRENTMONTHTRANSACTIONS,
    UPDATEPASSWORD,
    RETRIEVEUSERPROFILE,
    UPDATEPROFILE,
    UPDATEPIN,
    TRANSFERFUNDS,
    MANAGEALERTS,
    UPDATEALERTS,
    VERIFYREGISTEREDCARDPIN,
    CARDDETAILS,
    USERDETAILS,
    DIRECTDEPOSIT,
    REFRESH,
    LOGOUT,
    CARDLOST,
    CARDFOUND,
    ACTIVATECARD,
    LOADQUESTIONS,
    CREATEUSERACCOUNT,
    RESETPASSWORD,
    VERIFYCARDREGISTRATIONSTATUS,
    GETSECURITYQUESTIONS,
    VALIDATEQUESTIONS,
    RESETTINGPASSWORD,
    GETSECURITYQUESTIONSONE,
    GETSECURITYQUESTIONSTWO,
    GETSECURITYQUESTIONSTHREE
}
